apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
  namespace: nodejs
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container
          image: ${NODEJS_IMAGE}:${NODEJS_IMAGE_TAG}
          ports:
            - containerPort: 3000
      envFrom:
      - configMapRef:
          name: app-variables
