apiVersion: v2
name: nodejs-app-chart
description: A brief description of the purpose of the Helm chart.
type: application
version: 1.0.0
appVersion: 1.0.0
maintainers:
  - name: "Todor Ivanov"
    email: maintainer-email@example.com