general:
  namespace: "nodejs"
mongodb: 
  pod_name: "monogodb"
  image: "mongo:latest"
  replicaCount: 1 
nodejs:
  pod_name: "nodejs"
  image: "node:hydrogen-buster-slim"
  replicaCount: 3 
storage: 
  disk_space: "1Gi"