apiVersion: v1
kind: Service 
metadata: 
  name: nodejs-app-service
  namespace: {{ .Values.general.namespace }}
spec: 
  selector: 
    app: {{ .Values.nodejs.pod_name }} 
  ports:
    - protocol: TCP
      port: 80 # Port exposed to the world 
      targetPort: 3000 # Port the NodeJS app is listening on