apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.pod_name }}
  namespace: {{ .Values.general.namespace }}
spec:
  selector:
    app: {{ .Values.mongodb.pod_name }}
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP