apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.mongodb.pod_name }}
  namespace: {{ .Values.general.namespace }}
spec: 
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.mongodb.pod_name }}
  template:
    metadata:
      labels:
        component: {{ .Values.mongodb.pod_name }}
    spec:
      containers:
        - name: {{ .Values.mongodb.pod_name }}
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
      volumes:
          - name: mongodb-storage
            persistentVolumeClaim:
              claimName: mongodb-pvc